-- 外键约束（所有表创建完成后统一添加）

ALTER TABLE users ADD CONSTRAINT fk_users_organization_id FOREIGN KEY (organization_id) REFERENCES organizations(id);
ALTER TABLE user_roles ADD CONSTRAINT fk_user_roles_user_id FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE;
ALTER TABLE user_roles ADD CONSTRAINT fk_user_roles_role_id FOREIGN KEY (role_id) REFERENCES roles(id);
ALTER TABLE fonds ADD CONSTRAINT fk_fonds_organization_id FOREIGN KEY (organization_id) REFERENCES organizations(id);
ALTER TABLE storage_locations ADD CONSTRAINT fk_storage_locations_room_id FOREIGN KEY (room_id) REFERENCES warehouse_rooms(id);
ALTER TABLE archive_boxes ADD CONSTRAINT fk_archive_boxes_location_id FOREIGN KEY (location_id) REFERENCES storage_locations(id);
ALTER TABLE archive_boxes ADD CONSTRAINT fk_archive_boxes_category_id FOREIGN KEY (category_id) REFERENCES categories(id);
ALTER TABLE archive_boxes ADD CONSTRAINT fk_archive_boxes_fonds_id FOREIGN KEY (fonds_id) REFERENCES fonds(id);
ALTER TABLE intake_batches ADD CONSTRAINT fk_intake_batches_organization_id FOREIGN KEY (organization_id) REFERENCES organizations(id);
ALTER TABLE intake_batches ADD CONSTRAINT fk_intake_batches_public_user_id FOREIGN KEY (public_user_id) REFERENCES users(id);
ALTER TABLE intake_batches ADD CONSTRAINT fk_intake_batches_accepted_by FOREIGN KEY (accepted_by) REFERENCES users(id);
ALTER TABLE intake_items ADD CONSTRAINT fk_intake_items_batch_id FOREIGN KEY (batch_id) REFERENCES intake_batches(id) ON DELETE CASCADE;
ALTER TABLE intake_items ADD CONSTRAINT fk_intake_items_confirmed_category_id FOREIGN KEY (confirmed_category_id) REFERENCES categories(id);
ALTER TABLE compilations ADD CONSTRAINT fk_compilations_created_by FOREIGN KEY (created_by) REFERENCES users(id);
ALTER TABLE compilations ADD CONSTRAINT fk_compilations_updated_by FOREIGN KEY (updated_by) REFERENCES users(id);
ALTER TABLE archives ADD CONSTRAINT fk_archives_category_id FOREIGN KEY (category_id) REFERENCES categories(id);
ALTER TABLE archives ADD CONSTRAINT fk_archives_source_batch_id FOREIGN KEY (source_batch_id) REFERENCES intake_batches(id);
ALTER TABLE archives ADD CONSTRAINT fk_archives_source_item_id FOREIGN KEY (source_item_id) REFERENCES intake_items(id);
ALTER TABLE archives ADD CONSTRAINT fk_archives_source_compilation_id FOREIGN KEY (source_compilation_id) REFERENCES compilations(id);
ALTER TABLE archives ADD CONSTRAINT fk_archives_organization_id FOREIGN KEY (organization_id) REFERENCES organizations(id);
ALTER TABLE archives ADD CONSTRAINT fk_archives_fonds_id FOREIGN KEY (fonds_id) REFERENCES fonds(id);
ALTER TABLE archives ADD CONSTRAINT fk_archives_created_by FOREIGN KEY (created_by) REFERENCES users(id);
ALTER TABLE archives ADD CONSTRAINT fk_archives_updated_by FOREIGN KEY (updated_by) REFERENCES users(id);
ALTER TABLE archive_files ADD CONSTRAINT fk_archive_files_archive_id FOREIGN KEY (archive_id) REFERENCES archives(id) ON DELETE CASCADE;
ALTER TABLE archive_files ADD CONSTRAINT fk_archive_files_deleted_by FOREIGN KEY (deleted_by) REFERENCES users(id);
ALTER TABLE archive_files ADD CONSTRAINT fk_archive_files_created_by FOREIGN KEY (created_by) REFERENCES users(id);
ALTER TABLE archive_files ADD CONSTRAINT fk_archive_files_updated_by FOREIGN KEY (updated_by) REFERENCES users(id);
ALTER TABLE archive_tags ADD CONSTRAINT fk_archive_tags_archive_id FOREIGN KEY (archive_id) REFERENCES archives(id) ON DELETE CASCADE;
ALTER TABLE archive_tags ADD CONSTRAINT fk_archive_tags_tag_id FOREIGN KEY (tag_id) REFERENCES tags(id) ON DELETE CASCADE;
ALTER TABLE staging_files ADD CONSTRAINT fk_staging_files_batch_id FOREIGN KEY (batch_id) REFERENCES intake_batches(id) ON DELETE CASCADE;
ALTER TABLE staging_files ADD CONSTRAINT fk_staging_files_item_id FOREIGN KEY (item_id) REFERENCES intake_items(id) ON DELETE SET NULL;
ALTER TABLE staging_files ADD CONSTRAINT fk_staging_files_uploaded_by FOREIGN KEY (uploaded_by) REFERENCES users(id);
ALTER TABLE staging_files ADD CONSTRAINT fk_staging_files_archived_file_id FOREIGN KEY (archived_file_id) REFERENCES archive_files(id);
ALTER TABLE business_attachments ADD CONSTRAINT fk_business_attachments_uploaded_by FOREIGN KEY (uploaded_by) REFERENCES users(id);
ALTER TABLE archive_box_items ADD CONSTRAINT fk_archive_box_items_box_id FOREIGN KEY (box_id) REFERENCES archive_boxes(id) ON DELETE CASCADE;
ALTER TABLE archive_box_items ADD CONSTRAINT fk_archive_box_items_archive_id FOREIGN KEY (archive_id) REFERENCES archives(id) ON DELETE CASCADE;
ALTER TABLE borrow_requests ADD CONSTRAINT fk_borrow_requests_archive_id FOREIGN KEY (archive_id) REFERENCES archives(id);
ALTER TABLE borrow_requests ADD CONSTRAINT fk_borrow_requests_borrower_id FOREIGN KEY (borrower_id) REFERENCES users(id);
ALTER TABLE borrow_requests ADD CONSTRAINT fk_borrow_requests_approved_by FOREIGN KEY (approved_by) REFERENCES users(id);
ALTER TABLE borrow_requests ADD CONSTRAINT fk_borrow_requests_checked_out_by FOREIGN KEY (checked_out_by) REFERENCES users(id);
ALTER TABLE borrow_requests ADD CONSTRAINT fk_borrow_requests_returned_by FOREIGN KEY (returned_by) REFERENCES users(id);
ALTER TABLE approval_requests ADD CONSTRAINT fk_approval_requests_evidence_archive_id FOREIGN KEY (evidence_archive_id) REFERENCES archives(id);
ALTER TABLE approval_requests ADD CONSTRAINT fk_approval_requests_submitted_by FOREIGN KEY (submitted_by) REFERENCES users(id);
ALTER TABLE approval_requests ADD CONSTRAINT fk_approval_requests_approved_by FOREIGN KEY (approved_by) REFERENCES users(id);
ALTER TABLE archive_change_logs ADD CONSTRAINT fk_archive_change_logs_archive_id FOREIGN KEY (archive_id) REFERENCES archives(id) ON DELETE CASCADE;
ALTER TABLE archive_change_logs ADD CONSTRAINT fk_archive_change_logs_approval_request_id FOREIGN KEY (approval_request_id) REFERENCES approval_requests(id);
ALTER TABLE archive_change_logs ADD CONSTRAINT fk_archive_change_logs_changed_by FOREIGN KEY (changed_by) REFERENCES users(id);
ALTER TABLE appraisal_batches ADD CONSTRAINT fk_appraisal_batches_category_id FOREIGN KEY (category_id) REFERENCES categories(id);
ALTER TABLE appraisal_batches ADD CONSTRAINT fk_appraisal_batches_created_by FOREIGN KEY (created_by) REFERENCES users(id);
ALTER TABLE appraisal_batches ADD CONSTRAINT fk_appraisal_batches_updated_by FOREIGN KEY (updated_by) REFERENCES users(id);
ALTER TABLE appraisal_items ADD CONSTRAINT fk_appraisal_items_batch_id FOREIGN KEY (batch_id) REFERENCES appraisal_batches(id) ON DELETE CASCADE;
ALTER TABLE appraisal_items ADD CONSTRAINT fk_appraisal_items_archive_id FOREIGN KEY (archive_id) REFERENCES archives(id);
ALTER TABLE appraisal_items ADD CONSTRAINT fk_appraisal_items_appraised_by FOREIGN KEY (appraised_by) REFERENCES users(id);
ALTER TABLE destruction_lists ADD CONSTRAINT fk_destruction_lists_appraisal_batch_id FOREIGN KEY (appraisal_batch_id) REFERENCES appraisal_batches(id);
ALTER TABLE destruction_lists ADD CONSTRAINT fk_destruction_lists_approval_request_id FOREIGN KEY (approval_request_id) REFERENCES approval_requests(id);
ALTER TABLE destruction_lists ADD CONSTRAINT fk_destruction_lists_created_by FOREIGN KEY (created_by) REFERENCES users(id);
ALTER TABLE destruction_lists ADD CONSTRAINT fk_destruction_lists_updated_by FOREIGN KEY (updated_by) REFERENCES users(id);
ALTER TABLE destruction_items ADD CONSTRAINT fk_destruction_items_destruction_list_id FOREIGN KEY (destruction_list_id) REFERENCES destruction_lists(id) ON DELETE CASCADE;
ALTER TABLE destruction_items ADD CONSTRAINT fk_destruction_items_archive_id FOREIGN KEY (archive_id) REFERENCES archives(id);
ALTER TABLE inventory_tasks ADD CONSTRAINT fk_inventory_tasks_room_id FOREIGN KEY (room_id) REFERENCES warehouse_rooms(id);
ALTER TABLE inventory_tasks ADD CONSTRAINT fk_inventory_tasks_category_id FOREIGN KEY (category_id) REFERENCES categories(id);
ALTER TABLE inventory_tasks ADD CONSTRAINT fk_inventory_tasks_created_by FOREIGN KEY (created_by) REFERENCES users(id);
ALTER TABLE inventory_tasks ADD CONSTRAINT fk_inventory_tasks_updated_by FOREIGN KEY (updated_by) REFERENCES users(id);
ALTER TABLE inventory_items ADD CONSTRAINT fk_inventory_items_task_id FOREIGN KEY (task_id) REFERENCES inventory_tasks(id) ON DELETE CASCADE;
ALTER TABLE inventory_items ADD CONSTRAINT fk_inventory_items_archive_id FOREIGN KEY (archive_id) REFERENCES archives(id);
ALTER TABLE inventory_items ADD CONSTRAINT fk_inventory_items_box_id FOREIGN KEY (box_id) REFERENCES archive_boxes(id);
ALTER TABLE inventory_items ADD CONSTRAINT fk_inventory_items_expected_location_id FOREIGN KEY (expected_location_id) REFERENCES storage_locations(id);
ALTER TABLE compilation_materials ADD CONSTRAINT fk_compilation_materials_compilation_id FOREIGN KEY (compilation_id) REFERENCES compilations(id) ON DELETE CASCADE;
ALTER TABLE compilation_materials ADD CONSTRAINT fk_compilation_materials_archive_id FOREIGN KEY (archive_id) REFERENCES archives(id);
ALTER TABLE analysis_tasks ADD CONSTRAINT fk_analysis_tasks_created_by FOREIGN KEY (created_by) REFERENCES users(id);
ALTER TABLE analysis_tasks ADD CONSTRAINT fk_analysis_tasks_updated_by FOREIGN KEY (updated_by) REFERENCES users(id);
ALTER TABLE analysis_items ADD CONSTRAINT fk_analysis_items_task_id FOREIGN KEY (task_id) REFERENCES analysis_tasks(id) ON DELETE CASCADE;
ALTER TABLE analysis_items ADD CONSTRAINT fk_analysis_items_archive_id FOREIGN KEY (archive_id) REFERENCES archives(id);
ALTER TABLE analysis_items ADD CONSTRAINT fk_analysis_items_handled_by FOREIGN KEY (handled_by) REFERENCES users(id);
ALTER TABLE ai_tasks ADD CONSTRAINT fk_ai_tasks_created_by FOREIGN KEY (created_by) REFERENCES users(id);
ALTER TABLE ai_task_batches ADD CONSTRAINT fk_ai_task_batches_task_id FOREIGN KEY (task_id) REFERENCES ai_tasks(id) ON DELETE CASCADE;
ALTER TABLE backup_tasks ADD CONSTRAINT fk_backup_tasks_created_by FOREIGN KEY (created_by) REFERENCES users(id);
ALTER TABLE backup_tasks ADD CONSTRAINT fk_backup_tasks_updated_by FOREIGN KEY (updated_by) REFERENCES users(id);
ALTER TABLE archive_access_logs ADD CONSTRAINT fk_archive_access_logs_user_id FOREIGN KEY (user_id) REFERENCES users(id);
ALTER TABLE archive_access_logs ADD CONSTRAINT fk_archive_access_logs_archive_id FOREIGN KEY (archive_id) REFERENCES archives(id);
ALTER TABLE archive_access_logs ADD CONSTRAINT fk_archive_access_logs_archive_file_id FOREIGN KEY (archive_file_id) REFERENCES archive_files(id);
ALTER TABLE audit_logs ADD CONSTRAINT fk_audit_logs_actor_user_id FOREIGN KEY (actor_user_id) REFERENCES users(id);
