-- 移交征集清单与暂存文件

CREATE TABLE intake_batches (
  id BIGSERIAL PRIMARY KEY,
  batch_no VARCHAR(50) NOT NULL,
  source_type VARCHAR(20) NOT NULL CHECK (source_type IN ('transfer','collection')),
  title TEXT NOT NULL,
  status VARCHAR(30) NOT NULL CHECK (status IN ('draft','pending_transfer','pending_contact','pending_receive','received','partially_received','rejected','archived','shelved')),
  organization_id BIGINT REFERENCES organizations(id),
  department_name TEXT,
  public_user_id BIGINT REFERENCES users(id),
  contact_name TEXT NOT NULL,
  contact_phone VARCHAR(30),
  archive_year INTEGER,
  expected_transfer_date DATE,
  scheduled_receive_at TIMESTAMPTZ,
  submitted_at TIMESTAMPTZ,
  accepted_by BIGINT REFERENCES users(id),
  accepted_at TIMESTAMPTZ,
  archived_at TIMESTAMPTZ,
  shelved_at TIMESTAMPTZ,
  latest_ai_task_id BIGINT,
  reject_reason TEXT,
  agreement_accepted_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  created_by BIGINT,
  updated_by BIGINT,
  deleted_at TIMESTAMPTZ,
  CONSTRAINT ck_intake_batch_source_owner CHECK (
    (source_type = 'transfer' AND organization_id IS NOT NULL AND public_user_id IS NULL)
    OR
    (source_type = 'collection' AND public_user_id IS NOT NULL)
  )
);

CREATE TABLE intake_items (
  id BIGSERIAL PRIMARY KEY,
  batch_id BIGINT NOT NULL REFERENCES intake_batches(id) ON DELETE CASCADE,
  item_no INTEGER NOT NULL CHECK (item_no > 0),
  status VARCHAR(30) NOT NULL DEFAULT 'draft' CHECK (status IN ('draft','pending_acceptance','accepted','rejected','pending_archive','archived')),
  input_title TEXT NOT NULL,
  page_count INTEGER CHECK (page_count IS NULL OR page_count >= 0),
  retention_period VARCHAR(20) NOT NULL CHECK (retention_period IN ('10y','30y','permanent')),
  carrier_status VARCHAR(20) NOT NULL CHECK (carrier_status IN ('electronic','paper_electronic','paper')),
  security_level SMALLINT NOT NULL DEFAULT 0 CHECK (security_level BETWEEN 0 AND 4),
  open_status VARCHAR(20) NOT NULL DEFAULT 'open' CHECK (open_status IN ('open','closed')),
  allow_digitization BOOLEAN NOT NULL DEFAULT false,
  electronic_format VARCHAR(50),
  expected_filename TEXT,
  formed_date DATE,
  acceptance_note TEXT,
  reject_reason TEXT,
  file_match_status VARCHAR(30) NOT NULL DEFAULT 'none' CHECK (file_match_status IN ('none','matched','missing','duplicate','failed')),
  ai_suggestion JSONB,
  confirmed_title TEXT,
  confirmed_responsible_text TEXT,
  confirmed_formed_date DATE,
  confirmed_category_id SMALLINT REFERENCES categories(id),
  confirmed_tags JSONB,
  generated_archive_id BIGINT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  created_by BIGINT,
  updated_by BIGINT,
  deleted_at TIMESTAMPTZ
);

CREATE TABLE staging_files (
  id BIGSERIAL PRIMARY KEY,
  batch_id BIGINT NOT NULL REFERENCES intake_batches(id) ON DELETE CASCADE,
  item_id BIGINT REFERENCES intake_items(id) ON DELETE SET NULL,
  upload_batch_no VARCHAR(80) NOT NULL,
  original_filename TEXT NOT NULL,
  file_ext VARCHAR(30),
  mime_type VARCHAR(120),
  file_size BIGINT NOT NULL CHECK (file_size >= 0),
  sha256 CHAR(64),
  bucket_name VARCHAR(100) NOT NULL,
  object_key TEXT NOT NULL,
  match_status VARCHAR(30) NOT NULL CHECK (match_status IN ('unmatched','matched','duplicate','failed_check','archived','deleted')),
  scan_result VARCHAR(20) NOT NULL CHECK (scan_result IN ('pending','safe','infected','failed')),
  scan_message TEXT,
  check_summary JSONB,
  uploaded_by BIGINT REFERENCES users(id),
  uploaded_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  archived_file_id BIGINT REFERENCES archive_files(id),
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  created_by BIGINT,
  updated_by BIGINT,
  deleted_at TIMESTAMPTZ
);

CREATE TABLE business_attachments (
  id BIGSERIAL PRIMARY KEY,
  business_type VARCHAR(50) NOT NULL,
  business_id BIGINT NOT NULL,
  attachment_type VARCHAR(50) NOT NULL,
  bucket_name VARCHAR(100) NOT NULL,
  object_key TEXT NOT NULL,
  original_filename TEXT NOT NULL,
  file_ext VARCHAR(30),
  mime_type VARCHAR(120),
  file_size BIGINT NOT NULL CHECK (file_size >= 0),
  sha256 CHAR(64),
  scan_result VARCHAR(20) NOT NULL DEFAULT 'pending' CHECK (scan_result IN ('pending','safe','infected','failed')),
  scan_message TEXT,
  file_status VARCHAR(20) NOT NULL DEFAULT 'normal' CHECK (file_status IN ('normal','deleted')),
  uploaded_by BIGINT REFERENCES users(id),
  uploaded_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  created_by BIGINT,
  updated_by BIGINT,
  deleted_at TIMESTAMPTZ
);
